# Generated by Django 4.0.4 on 2022-06-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prop_a', models.CharField(max_length=40)),
                ('localidad_a', models.CharField(max_length=40)),
                ('barrio_a', models.CharField(max_length=40)),
                ('cant_dormi_a', models.IntegerField()),
                ('estado_a', models.BooleanField()),
                ('otro_cha_a', models.CharField(max_length=40)),
                ('otro_ent_a', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prop_t', models.CharField(max_length=40)),
                ('localidad_t', models.CharField(max_length=40)),
                ('barrio_t', models.CharField(max_length=40)),
                ('cant_dormi_t', models.IntegerField()),
                ('estado_t', models.BooleanField()),
                ('otro_cha_t', models.CharField(max_length=40)),
                ('otro_ent_t', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prop_v', models.CharField(max_length=40)),
                ('localidad_v', models.CharField(max_length=40)),
                ('barrio_v', models.CharField(max_length=40)),
                ('cant_dormi_v', models.IntegerField()),
                ('estado_v', models.BooleanField()),
                ('otro_cha_v', models.CharField(max_length=40)),
                ('otro_ent_v', models.IntegerField()),
            ],
        ),
    ]
