# Generated by Django 4.0.4 on 2022-06-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inmo_gg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='descrp_a',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='turismo',
            name='descrp_t',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='descrp_v',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
