# Generated by Django 4.0.4 on 2022-06-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inmo_gg', '0002_alquiler_descrp_a_turismo_descrp_t_venta_descrp_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='descrp_a',
            field=models.TextField(default='anything', max_length=400),
        ),
        migrations.AlterField(
            model_name='turismo',
            name='descrp_t',
            field=models.TextField(default='anything', max_length=400),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descrp_v',
            field=models.TextField(default='anything', max_length=400),
        ),
    ]
